//Register User
export const REGISTER_USER = "REGISTER_USER";
export const REGISTER_USER_SUCCESS = "REGISTER_USER_SUCCESS";
export const REGISTER_USER_ERROR = "REGISTER_USER_ERROR";

//Login User
export const LOGIN_USER = "LOGIN_USER";
export const RECOVERY_PASS = "RECOVERY_PASS";
export const LOGIN_USER_SUCCESS = "LOGIN_USER_SUCCESS";
export const LOGIN_USER_ERROR = "LOGIN_USER_ERROR";
export const DATA_USER = "DATA_USER";

//Slides
export const SET_SLIDES_DOWN = "SET_SLIDES_DOWN";
export const SET_SLIDES_DOWN_RESPONSIVE = "SET_SLIDES_DOWN_RESPONSIVE";
export const SET_SLIDES_UP = "SET_SLIDES_UP";
export const SET_SLIDES_UP_RESPONSIVE = "SET_SLIDES_UP_RESPONSIVE";

//Products
export const GET_PRODS = "GET_PRODS";

//Users
export const GET_USERS = "GET_USERS";
export const SET_HISTORY_INVOICE_BY_USER = "SET_HISTORY_INVOICE_BY_USER";
export const SET_REDEEM_LIST = "SET_REDEEM_LIST";

//Subsidiary
export const SET_SUBSIDIARIES = "SET_SUBSIDIARIES";

//Errors
export const ERROR_MESSAGE = "ERROR_MESSAGE";

//Message
export const MESSAGE = "MESSAGE";

//Session
export const SET_SESSION_POINTS = "SET_SESSION_POINTS";

//Invoices
export const SET_HISTORY_INVOICE = "SET_HISTORY_INVOICE";
